<?php use Alchemy\Mvc\Adapter\PhtmlView; ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title><?php PhtmlView::block('title', 'Welcome!')?></title>
        <link rel="stylesheet" type="text/css" href="<?php echo $baseurl?>assets/framework/css/style.css">
        <!--[if lt IE 9]>
        <script src="<?php echo $baseurl?>assets/framework/js/html5.js"></script>
        <![endif]-->
        <style>
        pre{
            background-color: inherit;
            border: 0px;
            color: inherit;
            font: inherit;
        }
        </style>
    </head>

    <body>
        <div class="container">
            <?php PhtmlView::block('body', '')?>
            <footer>
                <p>Powered by <a href="https://www.phpalchemy.org">PHPAlchemy Framework</a></p>
            </footer>
        </div>
        <script src="<?php echo $baseurl?>assets/framework/js/jquery.js"></script>
        <script src="<?php echo $baseurl?>assets/framework/js/bootstrap.js"></script>
        <script src="<?php echo $baseurl?>assets/framework/js/codemirror.js"></script>
        <script src="<?php echo $baseurl?>assets/framework/js/main.js"></script>
    </body>
</html>

