<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-29 at 10:55:36.
 */
class ClassLoaderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ClassLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new ClassLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ClassLoader::setNamespaceSeparator
     * @todo   Implement testSetNamespaceSeparator().
     */
    public function testSetNamespaceSeparator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::getNamespaceSeparator
     * @todo   Implement testGetNamespaceSeparator().
     */
    public function testGetNamespaceSeparator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::setIncludePath
     * @todo   Implement testSetIncludePath().
     */
    public function testSetIncludePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::getIncludePath
     * @todo   Implement testGetIncludePath().
     */
    public function testGetIncludePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::setFileExtension
     * @todo   Implement testSetFileExtension().
     */
    public function testSetFileExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::getFileExtension
     * @todo   Implement testGetFileExtension().
     */
    public function testGetFileExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::unregister
     * @todo   Implement testUnregister().
     */
    public function testUnregister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ClassLoader::loadClass
     * @todo   Implement testLoadClass().
     */
    public function testLoadClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
