<?php
/**
 * Autogenerated By PHPAlchemy Web Framework
 *
 * file: router.php
 */

if (file_exists($_SERVER['SCRIPT_FILENAME'])) {
    return false;
} else {
    $_SERVER['SCRIPT_FILENAME'] = $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . '{srvFile}';
    
    require '{srvFile}';
}